### ISSUE TITLE
$bypass always set to FALSE ?

### ISSUE THREAD

**Issue by ghost** [lonnieezell/Ocular-Template-Library#4] opened 2010-07-21 03:24 UTC
The $bypass always set to FALSE, the effect is the view rendered first before the layout (the yield method $this->template->yield not running)
then i hardcoded the function (yield) i set the $bypass to TRUE, then is running.

public function yield($bypass=FALSE)  { 
$this->_mark('Template_Yield_start');
// If we've cached the layout, we don't return anything except the 
// yield function itself.
if ($bypass === TRUE) { // I CHANGED TO TRUE
return '{yield}';
} else {
$this->_render_view($this->current_view, $this->cache_view);
}
$this->_mark('Template_Yield_end');
}

**Comment by lonnieezell** [comment] 2010-07-21 17:32
Which version are you using? This should be fixed in the current version.

**Comment by ghost** [comment] 2010-07-23 06:35
im using > 2.0.4
i tried the newest version 2.1.1, but it showing nothing...

**Comment by alertmybanjos** [comment] 2010-09-12 19:48
I ran into this same problem.  Looks like this hasn't been fixed yet, but I can confirm that changing "false" to "true" in line 316 solved it for me too

**Closed as completed** 2010-10-02 01:26 UTC
